site_name: Researchdata.se documentation
theme: material
repo_url: https://github.com/researchdata-se/docs.researchdata.se/
edit_uri: edit/main/docs/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences